apiVersion: v1
kind: Service
metadata:
  name: tenant-b-ml-inference-svc
  namespace: tenant-b
  labels:
    app: ml-inference
    tenant: tenant-b
spec:
  selector:
    app: ml-inference
    tenant: tenant-b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP

